// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwUfNX77fGSlKtOj7jUBxiiXEvcf0hAbU',
    appId: '1:640323886751:web:2aaeadf5ed9f60d3414caa',
    messagingSenderId: '640323886751',
    projectId: 'voyage-368821',
    authDomain: 'voyage-368821.firebaseapp.com',
    storageBucket: 'voyage-368821.appspot.com',
    measurementId: 'G-FH8243QJJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEJuxeo2m0d3g6sejjNz6bxfcCwOqboTg',
    appId: '1:640323886751:android:7cf7c9e219a0fb45414caa',
    messagingSenderId: '640323886751',
    projectId: 'voyage-368821',
    storageBucket: 'voyage-368821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH74ASA3YxvO2CWr5Pu6bkvvezaLsp7OI',
    appId: '1:640323886751:ios:d44b7062fd837514414caa',
    messagingSenderId: '640323886751',
    projectId: 'voyage-368821',
    storageBucket: 'voyage-368821.appspot.com',
    iosClientId: '640323886751-dqanv352u3n2mf9n61ip6dfdic87b7vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH74ASA3YxvO2CWr5Pu6bkvvezaLsp7OI',
    appId: '1:640323886751:ios:d44b7062fd837514414caa',
    messagingSenderId: '640323886751',
    projectId: 'voyage-368821',
    storageBucket: 'voyage-368821.appspot.com',
    iosClientId: '640323886751-dqanv352u3n2mf9n61ip6dfdic87b7vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage',
  );
}
